version: '3'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
